Fix logging missing argument (#94)
```
TypeError: warn_once() missing 1 required positional argument: 'msg'
```

https://github.com/huggingface/optimum/blob/79e8cd85a2ebf074c45e3046448c36f5d28e8766/optimum/utils/logging.py#L271